var mathematics = 75.25;
var biology = 65;
var chemistry = 80;
var physics = 35.45;
var bangla = 99.50;
var totalmarks = (mathematics + biology + chemistry + physics + bangla);
console.log(totalmarks);
var averagemarks = totalmarks / 5;
console.log(averagemarks);
console.log(averagemarks.toFixed(2));